# Generated by Django 5.2.11 on 2026-03-05 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='calendar_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='google_event_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='meet_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
