# Generated by Django 5.2.11 on 2026-02-16 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(help_text='Customer phone number for outbound calls', max_length=50)),
                ('call_type', models.CharField(choices=[('outbound', 'Outbound Phone Call'), ('inbound', 'Inbound Phone Call'), ('browser', 'Browser Voice Chat')], default='browser', help_text='Type of call (outbound, inbound, or browser)', max_length=20)),
                ('conversation_id', models.CharField(help_text='Unique conversation ID from ElevenLabs', max_length=255, unique=True)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('failed', 'Failed')], default='initiated', help_text='Current status of the call', max_length=50)),
                ('transcript', models.TextField(blank=True, help_text='Full conversation transcript', null=True)),
                ('duration_seconds', models.IntegerField(blank=True, help_text='Call duration in seconds', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional context data for the call')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the call was initiated')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the call record was last updated')),
                ('order', models.ForeignKey(blank=True, help_text='Associated order if this call is order-related', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calls', to='menu.order')),
            ],
            options={
                'verbose_name': 'Call',
                'verbose_name_plural': 'Calls',
                'ordering': ['-created_at'],
            },
        ),
    ]
